using SoulsFormats;
using System.Collections.Generic;
using System.Numerics;

namespace HKX2
{
    public partial class hclBendStiffnessConstraintSetMxBatch : IHavokObject
    {
        public virtual uint Signature { get => 962421569; }
        
        public float m_weightsA_0;
        public float m_weightsA_1;
        public float m_weightsA_2;
        public float m_weightsA_3;
        public float m_weightsA_4;
        public float m_weightsA_5;
        public float m_weightsA_6;
        public float m_weightsA_7;
        public float m_weightsA_8;
        public float m_weightsA_9;
        public float m_weightsA_10;
        public float m_weightsA_11;
        public float m_weightsA_12;
        public float m_weightsA_13;
        public float m_weightsA_14;
        public float m_weightsA_15;
        public float m_weightsB_0;
        public float m_weightsB_1;
        public float m_weightsB_2;
        public float m_weightsB_3;
        public float m_weightsB_4;
        public float m_weightsB_5;
        public float m_weightsB_6;
        public float m_weightsB_7;
        public float m_weightsB_8;
        public float m_weightsB_9;
        public float m_weightsB_10;
        public float m_weightsB_11;
        public float m_weightsB_12;
        public float m_weightsB_13;
        public float m_weightsB_14;
        public float m_weightsB_15;
        public float m_weightsC_0;
        public float m_weightsC_1;
        public float m_weightsC_2;
        public float m_weightsC_3;
        public float m_weightsC_4;
        public float m_weightsC_5;
        public float m_weightsC_6;
        public float m_weightsC_7;
        public float m_weightsC_8;
        public float m_weightsC_9;
        public float m_weightsC_10;
        public float m_weightsC_11;
        public float m_weightsC_12;
        public float m_weightsC_13;
        public float m_weightsC_14;
        public float m_weightsC_15;
        public float m_weightsD_0;
        public float m_weightsD_1;
        public float m_weightsD_2;
        public float m_weightsD_3;
        public float m_weightsD_4;
        public float m_weightsD_5;
        public float m_weightsD_6;
        public float m_weightsD_7;
        public float m_weightsD_8;
        public float m_weightsD_9;
        public float m_weightsD_10;
        public float m_weightsD_11;
        public float m_weightsD_12;
        public float m_weightsD_13;
        public float m_weightsD_14;
        public float m_weightsD_15;
        public float m_bendStiffnesses_0;
        public float m_bendStiffnesses_1;
        public float m_bendStiffnesses_2;
        public float m_bendStiffnesses_3;
        public float m_bendStiffnesses_4;
        public float m_bendStiffnesses_5;
        public float m_bendStiffnesses_6;
        public float m_bendStiffnesses_7;
        public float m_bendStiffnesses_8;
        public float m_bendStiffnesses_9;
        public float m_bendStiffnesses_10;
        public float m_bendStiffnesses_11;
        public float m_bendStiffnesses_12;
        public float m_bendStiffnesses_13;
        public float m_bendStiffnesses_14;
        public float m_bendStiffnesses_15;
        public float m_restCurvatures_0;
        public float m_restCurvatures_1;
        public float m_restCurvatures_2;
        public float m_restCurvatures_3;
        public float m_restCurvatures_4;
        public float m_restCurvatures_5;
        public float m_restCurvatures_6;
        public float m_restCurvatures_7;
        public float m_restCurvatures_8;
        public float m_restCurvatures_9;
        public float m_restCurvatures_10;
        public float m_restCurvatures_11;
        public float m_restCurvatures_12;
        public float m_restCurvatures_13;
        public float m_restCurvatures_14;
        public float m_restCurvatures_15;
        public float m_invMassesA_0;
        public float m_invMassesA_1;
        public float m_invMassesA_2;
        public float m_invMassesA_3;
        public float m_invMassesA_4;
        public float m_invMassesA_5;
        public float m_invMassesA_6;
        public float m_invMassesA_7;
        public float m_invMassesA_8;
        public float m_invMassesA_9;
        public float m_invMassesA_10;
        public float m_invMassesA_11;
        public float m_invMassesA_12;
        public float m_invMassesA_13;
        public float m_invMassesA_14;
        public float m_invMassesA_15;
        public float m_invMassesB_0;
        public float m_invMassesB_1;
        public float m_invMassesB_2;
        public float m_invMassesB_3;
        public float m_invMassesB_4;
        public float m_invMassesB_5;
        public float m_invMassesB_6;
        public float m_invMassesB_7;
        public float m_invMassesB_8;
        public float m_invMassesB_9;
        public float m_invMassesB_10;
        public float m_invMassesB_11;
        public float m_invMassesB_12;
        public float m_invMassesB_13;
        public float m_invMassesB_14;
        public float m_invMassesB_15;
        public float m_invMassesC_0;
        public float m_invMassesC_1;
        public float m_invMassesC_2;
        public float m_invMassesC_3;
        public float m_invMassesC_4;
        public float m_invMassesC_5;
        public float m_invMassesC_6;
        public float m_invMassesC_7;
        public float m_invMassesC_8;
        public float m_invMassesC_9;
        public float m_invMassesC_10;
        public float m_invMassesC_11;
        public float m_invMassesC_12;
        public float m_invMassesC_13;
        public float m_invMassesC_14;
        public float m_invMassesC_15;
        public float m_invMassesD_0;
        public float m_invMassesD_1;
        public float m_invMassesD_2;
        public float m_invMassesD_3;
        public float m_invMassesD_4;
        public float m_invMassesD_5;
        public float m_invMassesD_6;
        public float m_invMassesD_7;
        public float m_invMassesD_8;
        public float m_invMassesD_9;
        public float m_invMassesD_10;
        public float m_invMassesD_11;
        public float m_invMassesD_12;
        public float m_invMassesD_13;
        public float m_invMassesD_14;
        public float m_invMassesD_15;
        public ushort m_particlesA_0;
        public ushort m_particlesA_1;
        public ushort m_particlesA_2;
        public ushort m_particlesA_3;
        public ushort m_particlesA_4;
        public ushort m_particlesA_5;
        public ushort m_particlesA_6;
        public ushort m_particlesA_7;
        public ushort m_particlesA_8;
        public ushort m_particlesA_9;
        public ushort m_particlesA_10;
        public ushort m_particlesA_11;
        public ushort m_particlesA_12;
        public ushort m_particlesA_13;
        public ushort m_particlesA_14;
        public ushort m_particlesA_15;
        public ushort m_particlesB_0;
        public ushort m_particlesB_1;
        public ushort m_particlesB_2;
        public ushort m_particlesB_3;
        public ushort m_particlesB_4;
        public ushort m_particlesB_5;
        public ushort m_particlesB_6;
        public ushort m_particlesB_7;
        public ushort m_particlesB_8;
        public ushort m_particlesB_9;
        public ushort m_particlesB_10;
        public ushort m_particlesB_11;
        public ushort m_particlesB_12;
        public ushort m_particlesB_13;
        public ushort m_particlesB_14;
        public ushort m_particlesB_15;
        public ushort m_particlesC_0;
        public ushort m_particlesC_1;
        public ushort m_particlesC_2;
        public ushort m_particlesC_3;
        public ushort m_particlesC_4;
        public ushort m_particlesC_5;
        public ushort m_particlesC_6;
        public ushort m_particlesC_7;
        public ushort m_particlesC_8;
        public ushort m_particlesC_9;
        public ushort m_particlesC_10;
        public ushort m_particlesC_11;
        public ushort m_particlesC_12;
        public ushort m_particlesC_13;
        public ushort m_particlesC_14;
        public ushort m_particlesC_15;
        public ushort m_particlesD_0;
        public ushort m_particlesD_1;
        public ushort m_particlesD_2;
        public ushort m_particlesD_3;
        public ushort m_particlesD_4;
        public ushort m_particlesD_5;
        public ushort m_particlesD_6;
        public ushort m_particlesD_7;
        public ushort m_particlesD_8;
        public ushort m_particlesD_9;
        public ushort m_particlesD_10;
        public ushort m_particlesD_11;
        public ushort m_particlesD_12;
        public ushort m_particlesD_13;
        public ushort m_particlesD_14;
        public ushort m_particlesD_15;
        
        public virtual void Read(PackFileDeserializer des, BinaryReaderEx br)
        {
            m_weightsA_0 = br.ReadSingle();
            m_weightsA_1 = br.ReadSingle();
            m_weightsA_2 = br.ReadSingle();
            m_weightsA_3 = br.ReadSingle();
            m_weightsA_4 = br.ReadSingle();
            m_weightsA_5 = br.ReadSingle();
            m_weightsA_6 = br.ReadSingle();
            m_weightsA_7 = br.ReadSingle();
            m_weightsA_8 = br.ReadSingle();
            m_weightsA_9 = br.ReadSingle();
            m_weightsA_10 = br.ReadSingle();
            m_weightsA_11 = br.ReadSingle();
            m_weightsA_12 = br.ReadSingle();
            m_weightsA_13 = br.ReadSingle();
            m_weightsA_14 = br.ReadSingle();
            m_weightsA_15 = br.ReadSingle();
            m_weightsB_0 = br.ReadSingle();
            m_weightsB_1 = br.ReadSingle();
            m_weightsB_2 = br.ReadSingle();
            m_weightsB_3 = br.ReadSingle();
            m_weightsB_4 = br.ReadSingle();
            m_weightsB_5 = br.ReadSingle();
            m_weightsB_6 = br.ReadSingle();
            m_weightsB_7 = br.ReadSingle();
            m_weightsB_8 = br.ReadSingle();
            m_weightsB_9 = br.ReadSingle();
            m_weightsB_10 = br.ReadSingle();
            m_weightsB_11 = br.ReadSingle();
            m_weightsB_12 = br.ReadSingle();
            m_weightsB_13 = br.ReadSingle();
            m_weightsB_14 = br.ReadSingle();
            m_weightsB_15 = br.ReadSingle();
            m_weightsC_0 = br.ReadSingle();
            m_weightsC_1 = br.ReadSingle();
            m_weightsC_2 = br.ReadSingle();
            m_weightsC_3 = br.ReadSingle();
            m_weightsC_4 = br.ReadSingle();
            m_weightsC_5 = br.ReadSingle();
            m_weightsC_6 = br.ReadSingle();
            m_weightsC_7 = br.ReadSingle();
            m_weightsC_8 = br.ReadSingle();
            m_weightsC_9 = br.ReadSingle();
            m_weightsC_10 = br.ReadSingle();
            m_weightsC_11 = br.ReadSingle();
            m_weightsC_12 = br.ReadSingle();
            m_weightsC_13 = br.ReadSingle();
            m_weightsC_14 = br.ReadSingle();
            m_weightsC_15 = br.ReadSingle();
            m_weightsD_0 = br.ReadSingle();
            m_weightsD_1 = br.ReadSingle();
            m_weightsD_2 = br.ReadSingle();
            m_weightsD_3 = br.ReadSingle();
            m_weightsD_4 = br.ReadSingle();
            m_weightsD_5 = br.ReadSingle();
            m_weightsD_6 = br.ReadSingle();
            m_weightsD_7 = br.ReadSingle();
            m_weightsD_8 = br.ReadSingle();
            m_weightsD_9 = br.ReadSingle();
            m_weightsD_10 = br.ReadSingle();
            m_weightsD_11 = br.ReadSingle();
            m_weightsD_12 = br.ReadSingle();
            m_weightsD_13 = br.ReadSingle();
            m_weightsD_14 = br.ReadSingle();
            m_weightsD_15 = br.ReadSingle();
            m_bendStiffnesses_0 = br.ReadSingle();
            m_bendStiffnesses_1 = br.ReadSingle();
            m_bendStiffnesses_2 = br.ReadSingle();
            m_bendStiffnesses_3 = br.ReadSingle();
            m_bendStiffnesses_4 = br.ReadSingle();
            m_bendStiffnesses_5 = br.ReadSingle();
            m_bendStiffnesses_6 = br.ReadSingle();
            m_bendStiffnesses_7 = br.ReadSingle();
            m_bendStiffnesses_8 = br.ReadSingle();
            m_bendStiffnesses_9 = br.ReadSingle();
            m_bendStiffnesses_10 = br.ReadSingle();
            m_bendStiffnesses_11 = br.ReadSingle();
            m_bendStiffnesses_12 = br.ReadSingle();
            m_bendStiffnesses_13 = br.ReadSingle();
            m_bendStiffnesses_14 = br.ReadSingle();
            m_bendStiffnesses_15 = br.ReadSingle();
            m_restCurvatures_0 = br.ReadSingle();
            m_restCurvatures_1 = br.ReadSingle();
            m_restCurvatures_2 = br.ReadSingle();
            m_restCurvatures_3 = br.ReadSingle();
            m_restCurvatures_4 = br.ReadSingle();
            m_restCurvatures_5 = br.ReadSingle();
            m_restCurvatures_6 = br.ReadSingle();
            m_restCurvatures_7 = br.ReadSingle();
            m_restCurvatures_8 = br.ReadSingle();
            m_restCurvatures_9 = br.ReadSingle();
            m_restCurvatures_10 = br.ReadSingle();
            m_restCurvatures_11 = br.ReadSingle();
            m_restCurvatures_12 = br.ReadSingle();
            m_restCurvatures_13 = br.ReadSingle();
            m_restCurvatures_14 = br.ReadSingle();
            m_restCurvatures_15 = br.ReadSingle();
            m_invMassesA_0 = br.ReadSingle();
            m_invMassesA_1 = br.ReadSingle();
            m_invMassesA_2 = br.ReadSingle();
            m_invMassesA_3 = br.ReadSingle();
            m_invMassesA_4 = br.ReadSingle();
            m_invMassesA_5 = br.ReadSingle();
            m_invMassesA_6 = br.ReadSingle();
            m_invMassesA_7 = br.ReadSingle();
            m_invMassesA_8 = br.ReadSingle();
            m_invMassesA_9 = br.ReadSingle();
            m_invMassesA_10 = br.ReadSingle();
            m_invMassesA_11 = br.ReadSingle();
            m_invMassesA_12 = br.ReadSingle();
            m_invMassesA_13 = br.ReadSingle();
            m_invMassesA_14 = br.ReadSingle();
            m_invMassesA_15 = br.ReadSingle();
            m_invMassesB_0 = br.ReadSingle();
            m_invMassesB_1 = br.ReadSingle();
            m_invMassesB_2 = br.ReadSingle();
            m_invMassesB_3 = br.ReadSingle();
            m_invMassesB_4 = br.ReadSingle();
            m_invMassesB_5 = br.ReadSingle();
            m_invMassesB_6 = br.ReadSingle();
            m_invMassesB_7 = br.ReadSingle();
            m_invMassesB_8 = br.ReadSingle();
            m_invMassesB_9 = br.ReadSingle();
            m_invMassesB_10 = br.ReadSingle();
            m_invMassesB_11 = br.ReadSingle();
            m_invMassesB_12 = br.ReadSingle();
            m_invMassesB_13 = br.ReadSingle();
            m_invMassesB_14 = br.ReadSingle();
            m_invMassesB_15 = br.ReadSingle();
            m_invMassesC_0 = br.ReadSingle();
            m_invMassesC_1 = br.ReadSingle();
            m_invMassesC_2 = br.ReadSingle();
            m_invMassesC_3 = br.ReadSingle();
            m_invMassesC_4 = br.ReadSingle();
            m_invMassesC_5 = br.ReadSingle();
            m_invMassesC_6 = br.ReadSingle();
            m_invMassesC_7 = br.ReadSingle();
            m_invMassesC_8 = br.ReadSingle();
            m_invMassesC_9 = br.ReadSingle();
            m_invMassesC_10 = br.ReadSingle();
            m_invMassesC_11 = br.ReadSingle();
            m_invMassesC_12 = br.ReadSingle();
            m_invMassesC_13 = br.ReadSingle();
            m_invMassesC_14 = br.ReadSingle();
            m_invMassesC_15 = br.ReadSingle();
            m_invMassesD_0 = br.ReadSingle();
            m_invMassesD_1 = br.ReadSingle();
            m_invMassesD_2 = br.ReadSingle();
            m_invMassesD_3 = br.ReadSingle();
            m_invMassesD_4 = br.ReadSingle();
            m_invMassesD_5 = br.ReadSingle();
            m_invMassesD_6 = br.ReadSingle();
            m_invMassesD_7 = br.ReadSingle();
            m_invMassesD_8 = br.ReadSingle();
            m_invMassesD_9 = br.ReadSingle();
            m_invMassesD_10 = br.ReadSingle();
            m_invMassesD_11 = br.ReadSingle();
            m_invMassesD_12 = br.ReadSingle();
            m_invMassesD_13 = br.ReadSingle();
            m_invMassesD_14 = br.ReadSingle();
            m_invMassesD_15 = br.ReadSingle();
            m_particlesA_0 = br.ReadUInt16();
            m_particlesA_1 = br.ReadUInt16();
            m_particlesA_2 = br.ReadUInt16();
            m_particlesA_3 = br.ReadUInt16();
            m_particlesA_4 = br.ReadUInt16();
            m_particlesA_5 = br.ReadUInt16();
            m_particlesA_6 = br.ReadUInt16();
            m_particlesA_7 = br.ReadUInt16();
            m_particlesA_8 = br.ReadUInt16();
            m_particlesA_9 = br.ReadUInt16();
            m_particlesA_10 = br.ReadUInt16();
            m_particlesA_11 = br.ReadUInt16();
            m_particlesA_12 = br.ReadUInt16();
            m_particlesA_13 = br.ReadUInt16();
            m_particlesA_14 = br.ReadUInt16();
            m_particlesA_15 = br.ReadUInt16();
            m_particlesB_0 = br.ReadUInt16();
            m_particlesB_1 = br.ReadUInt16();
            m_particlesB_2 = br.ReadUInt16();
            m_particlesB_3 = br.ReadUInt16();
            m_particlesB_4 = br.ReadUInt16();
            m_particlesB_5 = br.ReadUInt16();
            m_particlesB_6 = br.ReadUInt16();
            m_particlesB_7 = br.ReadUInt16();
            m_particlesB_8 = br.ReadUInt16();
            m_particlesB_9 = br.ReadUInt16();
            m_particlesB_10 = br.ReadUInt16();
            m_particlesB_11 = br.ReadUInt16();
            m_particlesB_12 = br.ReadUInt16();
            m_particlesB_13 = br.ReadUInt16();
            m_particlesB_14 = br.ReadUInt16();
            m_particlesB_15 = br.ReadUInt16();
            m_particlesC_0 = br.ReadUInt16();
            m_particlesC_1 = br.ReadUInt16();
            m_particlesC_2 = br.ReadUInt16();
            m_particlesC_3 = br.ReadUInt16();
            m_particlesC_4 = br.ReadUInt16();
            m_particlesC_5 = br.ReadUInt16();
            m_particlesC_6 = br.ReadUInt16();
            m_particlesC_7 = br.ReadUInt16();
            m_particlesC_8 = br.ReadUInt16();
            m_particlesC_9 = br.ReadUInt16();
            m_particlesC_10 = br.ReadUInt16();
            m_particlesC_11 = br.ReadUInt16();
            m_particlesC_12 = br.ReadUInt16();
            m_particlesC_13 = br.ReadUInt16();
            m_particlesC_14 = br.ReadUInt16();
            m_particlesC_15 = br.ReadUInt16();
            m_particlesD_0 = br.ReadUInt16();
            m_particlesD_1 = br.ReadUInt16();
            m_particlesD_2 = br.ReadUInt16();
            m_particlesD_3 = br.ReadUInt16();
            m_particlesD_4 = br.ReadUInt16();
            m_particlesD_5 = br.ReadUInt16();
            m_particlesD_6 = br.ReadUInt16();
            m_particlesD_7 = br.ReadUInt16();
            m_particlesD_8 = br.ReadUInt16();
            m_particlesD_9 = br.ReadUInt16();
            m_particlesD_10 = br.ReadUInt16();
            m_particlesD_11 = br.ReadUInt16();
            m_particlesD_12 = br.ReadUInt16();
            m_particlesD_13 = br.ReadUInt16();
            m_particlesD_14 = br.ReadUInt16();
            m_particlesD_15 = br.ReadUInt16();
        }
        
        public virtual void Write(PackFileSerializer s, BinaryWriterEx bw)
        {
            bw.WriteSingle(m_weightsA_0);
            bw.WriteSingle(m_weightsA_1);
            bw.WriteSingle(m_weightsA_2);
            bw.WriteSingle(m_weightsA_3);
            bw.WriteSingle(m_weightsA_4);
            bw.WriteSingle(m_weightsA_5);
            bw.WriteSingle(m_weightsA_6);
            bw.WriteSingle(m_weightsA_7);
            bw.WriteSingle(m_weightsA_8);
            bw.WriteSingle(m_weightsA_9);
            bw.WriteSingle(m_weightsA_10);
            bw.WriteSingle(m_weightsA_11);
            bw.WriteSingle(m_weightsA_12);
            bw.WriteSingle(m_weightsA_13);
            bw.WriteSingle(m_weightsA_14);
            bw.WriteSingle(m_weightsA_15);
            bw.WriteSingle(m_weightsB_0);
            bw.WriteSingle(m_weightsB_1);
            bw.WriteSingle(m_weightsB_2);
            bw.WriteSingle(m_weightsB_3);
            bw.WriteSingle(m_weightsB_4);
            bw.WriteSingle(m_weightsB_5);
            bw.WriteSingle(m_weightsB_6);
            bw.WriteSingle(m_weightsB_7);
            bw.WriteSingle(m_weightsB_8);
            bw.WriteSingle(m_weightsB_9);
            bw.WriteSingle(m_weightsB_10);
            bw.WriteSingle(m_weightsB_11);
            bw.WriteSingle(m_weightsB_12);
            bw.WriteSingle(m_weightsB_13);
            bw.WriteSingle(m_weightsB_14);
            bw.WriteSingle(m_weightsB_15);
            bw.WriteSingle(m_weightsC_0);
            bw.WriteSingle(m_weightsC_1);
            bw.WriteSingle(m_weightsC_2);
            bw.WriteSingle(m_weightsC_3);
            bw.WriteSingle(m_weightsC_4);
            bw.WriteSingle(m_weightsC_5);
            bw.WriteSingle(m_weightsC_6);
            bw.WriteSingle(m_weightsC_7);
            bw.WriteSingle(m_weightsC_8);
            bw.WriteSingle(m_weightsC_9);
            bw.WriteSingle(m_weightsC_10);
            bw.WriteSingle(m_weightsC_11);
            bw.WriteSingle(m_weightsC_12);
            bw.WriteSingle(m_weightsC_13);
            bw.WriteSingle(m_weightsC_14);
            bw.WriteSingle(m_weightsC_15);
            bw.WriteSingle(m_weightsD_0);
            bw.WriteSingle(m_weightsD_1);
            bw.WriteSingle(m_weightsD_2);
            bw.WriteSingle(m_weightsD_3);
            bw.WriteSingle(m_weightsD_4);
            bw.WriteSingle(m_weightsD_5);
            bw.WriteSingle(m_weightsD_6);
            bw.WriteSingle(m_weightsD_7);
            bw.WriteSingle(m_weightsD_8);
            bw.WriteSingle(m_weightsD_9);
            bw.WriteSingle(m_weightsD_10);
            bw.WriteSingle(m_weightsD_11);
            bw.WriteSingle(m_weightsD_12);
            bw.WriteSingle(m_weightsD_13);
            bw.WriteSingle(m_weightsD_14);
            bw.WriteSingle(m_weightsD_15);
            bw.WriteSingle(m_bendStiffnesses_0);
            bw.WriteSingle(m_bendStiffnesses_1);
            bw.WriteSingle(m_bendStiffnesses_2);
            bw.WriteSingle(m_bendStiffnesses_3);
            bw.WriteSingle(m_bendStiffnesses_4);
            bw.WriteSingle(m_bendStiffnesses_5);
            bw.WriteSingle(m_bendStiffnesses_6);
            bw.WriteSingle(m_bendStiffnesses_7);
            bw.WriteSingle(m_bendStiffnesses_8);
            bw.WriteSingle(m_bendStiffnesses_9);
            bw.WriteSingle(m_bendStiffnesses_10);
            bw.WriteSingle(m_bendStiffnesses_11);
            bw.WriteSingle(m_bendStiffnesses_12);
            bw.WriteSingle(m_bendStiffnesses_13);
            bw.WriteSingle(m_bendStiffnesses_14);
            bw.WriteSingle(m_bendStiffnesses_15);
            bw.WriteSingle(m_restCurvatures_0);
            bw.WriteSingle(m_restCurvatures_1);
            bw.WriteSingle(m_restCurvatures_2);
            bw.WriteSingle(m_restCurvatures_3);
            bw.WriteSingle(m_restCurvatures_4);
            bw.WriteSingle(m_restCurvatures_5);
            bw.WriteSingle(m_restCurvatures_6);
            bw.WriteSingle(m_restCurvatures_7);
            bw.WriteSingle(m_restCurvatures_8);
            bw.WriteSingle(m_restCurvatures_9);
            bw.WriteSingle(m_restCurvatures_10);
            bw.WriteSingle(m_restCurvatures_11);
            bw.WriteSingle(m_restCurvatures_12);
            bw.WriteSingle(m_restCurvatures_13);
            bw.WriteSingle(m_restCurvatures_14);
            bw.WriteSingle(m_restCurvatures_15);
            bw.WriteSingle(m_invMassesA_0);
            bw.WriteSingle(m_invMassesA_1);
            bw.WriteSingle(m_invMassesA_2);
            bw.WriteSingle(m_invMassesA_3);
            bw.WriteSingle(m_invMassesA_4);
            bw.WriteSingle(m_invMassesA_5);
            bw.WriteSingle(m_invMassesA_6);
            bw.WriteSingle(m_invMassesA_7);
            bw.WriteSingle(m_invMassesA_8);
            bw.WriteSingle(m_invMassesA_9);
            bw.WriteSingle(m_invMassesA_10);
            bw.WriteSingle(m_invMassesA_11);
            bw.WriteSingle(m_invMassesA_12);
            bw.WriteSingle(m_invMassesA_13);
            bw.WriteSingle(m_invMassesA_14);
            bw.WriteSingle(m_invMassesA_15);
            bw.WriteSingle(m_invMassesB_0);
            bw.WriteSingle(m_invMassesB_1);
            bw.WriteSingle(m_invMassesB_2);
            bw.WriteSingle(m_invMassesB_3);
            bw.WriteSingle(m_invMassesB_4);
            bw.WriteSingle(m_invMassesB_5);
            bw.WriteSingle(m_invMassesB_6);
            bw.WriteSingle(m_invMassesB_7);
            bw.WriteSingle(m_invMassesB_8);
            bw.WriteSingle(m_invMassesB_9);
            bw.WriteSingle(m_invMassesB_10);
            bw.WriteSingle(m_invMassesB_11);
            bw.WriteSingle(m_invMassesB_12);
            bw.WriteSingle(m_invMassesB_13);
            bw.WriteSingle(m_invMassesB_14);
            bw.WriteSingle(m_invMassesB_15);
            bw.WriteSingle(m_invMassesC_0);
            bw.WriteSingle(m_invMassesC_1);
            bw.WriteSingle(m_invMassesC_2);
            bw.WriteSingle(m_invMassesC_3);
            bw.WriteSingle(m_invMassesC_4);
            bw.WriteSingle(m_invMassesC_5);
            bw.WriteSingle(m_invMassesC_6);
            bw.WriteSingle(m_invMassesC_7);
            bw.WriteSingle(m_invMassesC_8);
            bw.WriteSingle(m_invMassesC_9);
            bw.WriteSingle(m_invMassesC_10);
            bw.WriteSingle(m_invMassesC_11);
            bw.WriteSingle(m_invMassesC_12);
            bw.WriteSingle(m_invMassesC_13);
            bw.WriteSingle(m_invMassesC_14);
            bw.WriteSingle(m_invMassesC_15);
            bw.WriteSingle(m_invMassesD_0);
            bw.WriteSingle(m_invMassesD_1);
            bw.WriteSingle(m_invMassesD_2);
            bw.WriteSingle(m_invMassesD_3);
            bw.WriteSingle(m_invMassesD_4);
            bw.WriteSingle(m_invMassesD_5);
            bw.WriteSingle(m_invMassesD_6);
            bw.WriteSingle(m_invMassesD_7);
            bw.WriteSingle(m_invMassesD_8);
            bw.WriteSingle(m_invMassesD_9);
            bw.WriteSingle(m_invMassesD_10);
            bw.WriteSingle(m_invMassesD_11);
            bw.WriteSingle(m_invMassesD_12);
            bw.WriteSingle(m_invMassesD_13);
            bw.WriteSingle(m_invMassesD_14);
            bw.WriteSingle(m_invMassesD_15);
            bw.WriteUInt16(m_particlesA_0);
            bw.WriteUInt16(m_particlesA_1);
            bw.WriteUInt16(m_particlesA_2);
            bw.WriteUInt16(m_particlesA_3);
            bw.WriteUInt16(m_particlesA_4);
            bw.WriteUInt16(m_particlesA_5);
            bw.WriteUInt16(m_particlesA_6);
            bw.WriteUInt16(m_particlesA_7);
            bw.WriteUInt16(m_particlesA_8);
            bw.WriteUInt16(m_particlesA_9);
            bw.WriteUInt16(m_particlesA_10);
            bw.WriteUInt16(m_particlesA_11);
            bw.WriteUInt16(m_particlesA_12);
            bw.WriteUInt16(m_particlesA_13);
            bw.WriteUInt16(m_particlesA_14);
            bw.WriteUInt16(m_particlesA_15);
            bw.WriteUInt16(m_particlesB_0);
            bw.WriteUInt16(m_particlesB_1);
            bw.WriteUInt16(m_particlesB_2);
            bw.WriteUInt16(m_particlesB_3);
            bw.WriteUInt16(m_particlesB_4);
            bw.WriteUInt16(m_particlesB_5);
            bw.WriteUInt16(m_particlesB_6);
            bw.WriteUInt16(m_particlesB_7);
            bw.WriteUInt16(m_particlesB_8);
            bw.WriteUInt16(m_particlesB_9);
            bw.WriteUInt16(m_particlesB_10);
            bw.WriteUInt16(m_particlesB_11);
            bw.WriteUInt16(m_particlesB_12);
            bw.WriteUInt16(m_particlesB_13);
            bw.WriteUInt16(m_particlesB_14);
            bw.WriteUInt16(m_particlesB_15);
            bw.WriteUInt16(m_particlesC_0);
            bw.WriteUInt16(m_particlesC_1);
            bw.WriteUInt16(m_particlesC_2);
            bw.WriteUInt16(m_particlesC_3);
            bw.WriteUInt16(m_particlesC_4);
            bw.WriteUInt16(m_particlesC_5);
            bw.WriteUInt16(m_particlesC_6);
            bw.WriteUInt16(m_particlesC_7);
            bw.WriteUInt16(m_particlesC_8);
            bw.WriteUInt16(m_particlesC_9);
            bw.WriteUInt16(m_particlesC_10);
            bw.WriteUInt16(m_particlesC_11);
            bw.WriteUInt16(m_particlesC_12);
            bw.WriteUInt16(m_particlesC_13);
            bw.WriteUInt16(m_particlesC_14);
            bw.WriteUInt16(m_particlesC_15);
            bw.WriteUInt16(m_particlesD_0);
            bw.WriteUInt16(m_particlesD_1);
            bw.WriteUInt16(m_particlesD_2);
            bw.WriteUInt16(m_particlesD_3);
            bw.WriteUInt16(m_particlesD_4);
            bw.WriteUInt16(m_particlesD_5);
            bw.WriteUInt16(m_particlesD_6);
            bw.WriteUInt16(m_particlesD_7);
            bw.WriteUInt16(m_particlesD_8);
            bw.WriteUInt16(m_particlesD_9);
            bw.WriteUInt16(m_particlesD_10);
            bw.WriteUInt16(m_particlesD_11);
            bw.WriteUInt16(m_particlesD_12);
            bw.WriteUInt16(m_particlesD_13);
            bw.WriteUInt16(m_particlesD_14);
            bw.WriteUInt16(m_particlesD_15);
        }
    }
}
