using SoulsFormats;
using System.Collections.Generic;
using System.Numerics;

namespace HKX2
{
    public partial class hkpAgent1nSector : IHavokObject
    {
        public virtual uint Signature { get => 103212378; }
        
        public uint m_bytesAllocated;
        public uint m_pad0;
        public uint m_pad1;
        public uint m_pad2;
        public byte m_data_0;
        public byte m_data_1;
        public byte m_data_2;
        public byte m_data_3;
        public byte m_data_4;
        public byte m_data_5;
        public byte m_data_6;
        public byte m_data_7;
        public byte m_data_8;
        public byte m_data_9;
        public byte m_data_10;
        public byte m_data_11;
        public byte m_data_12;
        public byte m_data_13;
        public byte m_data_14;
        public byte m_data_15;
        public byte m_data_16;
        public byte m_data_17;
        public byte m_data_18;
        public byte m_data_19;
        public byte m_data_20;
        public byte m_data_21;
        public byte m_data_22;
        public byte m_data_23;
        public byte m_data_24;
        public byte m_data_25;
        public byte m_data_26;
        public byte m_data_27;
        public byte m_data_28;
        public byte m_data_29;
        public byte m_data_30;
        public byte m_data_31;
        public byte m_data_32;
        public byte m_data_33;
        public byte m_data_34;
        public byte m_data_35;
        public byte m_data_36;
        public byte m_data_37;
        public byte m_data_38;
        public byte m_data_39;
        public byte m_data_40;
        public byte m_data_41;
        public byte m_data_42;
        public byte m_data_43;
        public byte m_data_44;
        public byte m_data_45;
        public byte m_data_46;
        public byte m_data_47;
        public byte m_data_48;
        public byte m_data_49;
        public byte m_data_50;
        public byte m_data_51;
        public byte m_data_52;
        public byte m_data_53;
        public byte m_data_54;
        public byte m_data_55;
        public byte m_data_56;
        public byte m_data_57;
        public byte m_data_58;
        public byte m_data_59;
        public byte m_data_60;
        public byte m_data_61;
        public byte m_data_62;
        public byte m_data_63;
        public byte m_data_64;
        public byte m_data_65;
        public byte m_data_66;
        public byte m_data_67;
        public byte m_data_68;
        public byte m_data_69;
        public byte m_data_70;
        public byte m_data_71;
        public byte m_data_72;
        public byte m_data_73;
        public byte m_data_74;
        public byte m_data_75;
        public byte m_data_76;
        public byte m_data_77;
        public byte m_data_78;
        public byte m_data_79;
        public byte m_data_80;
        public byte m_data_81;
        public byte m_data_82;
        public byte m_data_83;
        public byte m_data_84;
        public byte m_data_85;
        public byte m_data_86;
        public byte m_data_87;
        public byte m_data_88;
        public byte m_data_89;
        public byte m_data_90;
        public byte m_data_91;
        public byte m_data_92;
        public byte m_data_93;
        public byte m_data_94;
        public byte m_data_95;
        public byte m_data_96;
        public byte m_data_97;
        public byte m_data_98;
        public byte m_data_99;
        public byte m_data_100;
        public byte m_data_101;
        public byte m_data_102;
        public byte m_data_103;
        public byte m_data_104;
        public byte m_data_105;
        public byte m_data_106;
        public byte m_data_107;
        public byte m_data_108;
        public byte m_data_109;
        public byte m_data_110;
        public byte m_data_111;
        public byte m_data_112;
        public byte m_data_113;
        public byte m_data_114;
        public byte m_data_115;
        public byte m_data_116;
        public byte m_data_117;
        public byte m_data_118;
        public byte m_data_119;
        public byte m_data_120;
        public byte m_data_121;
        public byte m_data_122;
        public byte m_data_123;
        public byte m_data_124;
        public byte m_data_125;
        public byte m_data_126;
        public byte m_data_127;
        public byte m_data_128;
        public byte m_data_129;
        public byte m_data_130;
        public byte m_data_131;
        public byte m_data_132;
        public byte m_data_133;
        public byte m_data_134;
        public byte m_data_135;
        public byte m_data_136;
        public byte m_data_137;
        public byte m_data_138;
        public byte m_data_139;
        public byte m_data_140;
        public byte m_data_141;
        public byte m_data_142;
        public byte m_data_143;
        public byte m_data_144;
        public byte m_data_145;
        public byte m_data_146;
        public byte m_data_147;
        public byte m_data_148;
        public byte m_data_149;
        public byte m_data_150;
        public byte m_data_151;
        public byte m_data_152;
        public byte m_data_153;
        public byte m_data_154;
        public byte m_data_155;
        public byte m_data_156;
        public byte m_data_157;
        public byte m_data_158;
        public byte m_data_159;
        public byte m_data_160;
        public byte m_data_161;
        public byte m_data_162;
        public byte m_data_163;
        public byte m_data_164;
        public byte m_data_165;
        public byte m_data_166;
        public byte m_data_167;
        public byte m_data_168;
        public byte m_data_169;
        public byte m_data_170;
        public byte m_data_171;
        public byte m_data_172;
        public byte m_data_173;
        public byte m_data_174;
        public byte m_data_175;
        public byte m_data_176;
        public byte m_data_177;
        public byte m_data_178;
        public byte m_data_179;
        public byte m_data_180;
        public byte m_data_181;
        public byte m_data_182;
        public byte m_data_183;
        public byte m_data_184;
        public byte m_data_185;
        public byte m_data_186;
        public byte m_data_187;
        public byte m_data_188;
        public byte m_data_189;
        public byte m_data_190;
        public byte m_data_191;
        public byte m_data_192;
        public byte m_data_193;
        public byte m_data_194;
        public byte m_data_195;
        public byte m_data_196;
        public byte m_data_197;
        public byte m_data_198;
        public byte m_data_199;
        public byte m_data_200;
        public byte m_data_201;
        public byte m_data_202;
        public byte m_data_203;
        public byte m_data_204;
        public byte m_data_205;
        public byte m_data_206;
        public byte m_data_207;
        public byte m_data_208;
        public byte m_data_209;
        public byte m_data_210;
        public byte m_data_211;
        public byte m_data_212;
        public byte m_data_213;
        public byte m_data_214;
        public byte m_data_215;
        public byte m_data_216;
        public byte m_data_217;
        public byte m_data_218;
        public byte m_data_219;
        public byte m_data_220;
        public byte m_data_221;
        public byte m_data_222;
        public byte m_data_223;
        public byte m_data_224;
        public byte m_data_225;
        public byte m_data_226;
        public byte m_data_227;
        public byte m_data_228;
        public byte m_data_229;
        public byte m_data_230;
        public byte m_data_231;
        public byte m_data_232;
        public byte m_data_233;
        public byte m_data_234;
        public byte m_data_235;
        public byte m_data_236;
        public byte m_data_237;
        public byte m_data_238;
        public byte m_data_239;
        public byte m_data_240;
        public byte m_data_241;
        public byte m_data_242;
        public byte m_data_243;
        public byte m_data_244;
        public byte m_data_245;
        public byte m_data_246;
        public byte m_data_247;
        public byte m_data_248;
        public byte m_data_249;
        public byte m_data_250;
        public byte m_data_251;
        public byte m_data_252;
        public byte m_data_253;
        public byte m_data_254;
        public byte m_data_255;
        public byte m_data_256;
        public byte m_data_257;
        public byte m_data_258;
        public byte m_data_259;
        public byte m_data_260;
        public byte m_data_261;
        public byte m_data_262;
        public byte m_data_263;
        public byte m_data_264;
        public byte m_data_265;
        public byte m_data_266;
        public byte m_data_267;
        public byte m_data_268;
        public byte m_data_269;
        public byte m_data_270;
        public byte m_data_271;
        public byte m_data_272;
        public byte m_data_273;
        public byte m_data_274;
        public byte m_data_275;
        public byte m_data_276;
        public byte m_data_277;
        public byte m_data_278;
        public byte m_data_279;
        public byte m_data_280;
        public byte m_data_281;
        public byte m_data_282;
        public byte m_data_283;
        public byte m_data_284;
        public byte m_data_285;
        public byte m_data_286;
        public byte m_data_287;
        public byte m_data_288;
        public byte m_data_289;
        public byte m_data_290;
        public byte m_data_291;
        public byte m_data_292;
        public byte m_data_293;
        public byte m_data_294;
        public byte m_data_295;
        public byte m_data_296;
        public byte m_data_297;
        public byte m_data_298;
        public byte m_data_299;
        public byte m_data_300;
        public byte m_data_301;
        public byte m_data_302;
        public byte m_data_303;
        public byte m_data_304;
        public byte m_data_305;
        public byte m_data_306;
        public byte m_data_307;
        public byte m_data_308;
        public byte m_data_309;
        public byte m_data_310;
        public byte m_data_311;
        public byte m_data_312;
        public byte m_data_313;
        public byte m_data_314;
        public byte m_data_315;
        public byte m_data_316;
        public byte m_data_317;
        public byte m_data_318;
        public byte m_data_319;
        public byte m_data_320;
        public byte m_data_321;
        public byte m_data_322;
        public byte m_data_323;
        public byte m_data_324;
        public byte m_data_325;
        public byte m_data_326;
        public byte m_data_327;
        public byte m_data_328;
        public byte m_data_329;
        public byte m_data_330;
        public byte m_data_331;
        public byte m_data_332;
        public byte m_data_333;
        public byte m_data_334;
        public byte m_data_335;
        public byte m_data_336;
        public byte m_data_337;
        public byte m_data_338;
        public byte m_data_339;
        public byte m_data_340;
        public byte m_data_341;
        public byte m_data_342;
        public byte m_data_343;
        public byte m_data_344;
        public byte m_data_345;
        public byte m_data_346;
        public byte m_data_347;
        public byte m_data_348;
        public byte m_data_349;
        public byte m_data_350;
        public byte m_data_351;
        public byte m_data_352;
        public byte m_data_353;
        public byte m_data_354;
        public byte m_data_355;
        public byte m_data_356;
        public byte m_data_357;
        public byte m_data_358;
        public byte m_data_359;
        public byte m_data_360;
        public byte m_data_361;
        public byte m_data_362;
        public byte m_data_363;
        public byte m_data_364;
        public byte m_data_365;
        public byte m_data_366;
        public byte m_data_367;
        public byte m_data_368;
        public byte m_data_369;
        public byte m_data_370;
        public byte m_data_371;
        public byte m_data_372;
        public byte m_data_373;
        public byte m_data_374;
        public byte m_data_375;
        public byte m_data_376;
        public byte m_data_377;
        public byte m_data_378;
        public byte m_data_379;
        public byte m_data_380;
        public byte m_data_381;
        public byte m_data_382;
        public byte m_data_383;
        public byte m_data_384;
        public byte m_data_385;
        public byte m_data_386;
        public byte m_data_387;
        public byte m_data_388;
        public byte m_data_389;
        public byte m_data_390;
        public byte m_data_391;
        public byte m_data_392;
        public byte m_data_393;
        public byte m_data_394;
        public byte m_data_395;
        public byte m_data_396;
        public byte m_data_397;
        public byte m_data_398;
        public byte m_data_399;
        public byte m_data_400;
        public byte m_data_401;
        public byte m_data_402;
        public byte m_data_403;
        public byte m_data_404;
        public byte m_data_405;
        public byte m_data_406;
        public byte m_data_407;
        public byte m_data_408;
        public byte m_data_409;
        public byte m_data_410;
        public byte m_data_411;
        public byte m_data_412;
        public byte m_data_413;
        public byte m_data_414;
        public byte m_data_415;
        public byte m_data_416;
        public byte m_data_417;
        public byte m_data_418;
        public byte m_data_419;
        public byte m_data_420;
        public byte m_data_421;
        public byte m_data_422;
        public byte m_data_423;
        public byte m_data_424;
        public byte m_data_425;
        public byte m_data_426;
        public byte m_data_427;
        public byte m_data_428;
        public byte m_data_429;
        public byte m_data_430;
        public byte m_data_431;
        public byte m_data_432;
        public byte m_data_433;
        public byte m_data_434;
        public byte m_data_435;
        public byte m_data_436;
        public byte m_data_437;
        public byte m_data_438;
        public byte m_data_439;
        public byte m_data_440;
        public byte m_data_441;
        public byte m_data_442;
        public byte m_data_443;
        public byte m_data_444;
        public byte m_data_445;
        public byte m_data_446;
        public byte m_data_447;
        public byte m_data_448;
        public byte m_data_449;
        public byte m_data_450;
        public byte m_data_451;
        public byte m_data_452;
        public byte m_data_453;
        public byte m_data_454;
        public byte m_data_455;
        public byte m_data_456;
        public byte m_data_457;
        public byte m_data_458;
        public byte m_data_459;
        public byte m_data_460;
        public byte m_data_461;
        public byte m_data_462;
        public byte m_data_463;
        public byte m_data_464;
        public byte m_data_465;
        public byte m_data_466;
        public byte m_data_467;
        public byte m_data_468;
        public byte m_data_469;
        public byte m_data_470;
        public byte m_data_471;
        public byte m_data_472;
        public byte m_data_473;
        public byte m_data_474;
        public byte m_data_475;
        public byte m_data_476;
        public byte m_data_477;
        public byte m_data_478;
        public byte m_data_479;
        public byte m_data_480;
        public byte m_data_481;
        public byte m_data_482;
        public byte m_data_483;
        public byte m_data_484;
        public byte m_data_485;
        public byte m_data_486;
        public byte m_data_487;
        public byte m_data_488;
        public byte m_data_489;
        public byte m_data_490;
        public byte m_data_491;
        public byte m_data_492;
        public byte m_data_493;
        public byte m_data_494;
        public byte m_data_495;
        
        public virtual void Read(PackFileDeserializer des, BinaryReaderEx br)
        {
            m_bytesAllocated = br.ReadUInt32();
            m_pad0 = br.ReadUInt32();
            m_pad1 = br.ReadUInt32();
            m_pad2 = br.ReadUInt32();
            m_data_0 = br.ReadByte();
            m_data_1 = br.ReadByte();
            m_data_2 = br.ReadByte();
            m_data_3 = br.ReadByte();
            m_data_4 = br.ReadByte();
            m_data_5 = br.ReadByte();
            m_data_6 = br.ReadByte();
            m_data_7 = br.ReadByte();
            m_data_8 = br.ReadByte();
            m_data_9 = br.ReadByte();
            m_data_10 = br.ReadByte();
            m_data_11 = br.ReadByte();
            m_data_12 = br.ReadByte();
            m_data_13 = br.ReadByte();
            m_data_14 = br.ReadByte();
            m_data_15 = br.ReadByte();
            m_data_16 = br.ReadByte();
            m_data_17 = br.ReadByte();
            m_data_18 = br.ReadByte();
            m_data_19 = br.ReadByte();
            m_data_20 = br.ReadByte();
            m_data_21 = br.ReadByte();
            m_data_22 = br.ReadByte();
            m_data_23 = br.ReadByte();
            m_data_24 = br.ReadByte();
            m_data_25 = br.ReadByte();
            m_data_26 = br.ReadByte();
            m_data_27 = br.ReadByte();
            m_data_28 = br.ReadByte();
            m_data_29 = br.ReadByte();
            m_data_30 = br.ReadByte();
            m_data_31 = br.ReadByte();
            m_data_32 = br.ReadByte();
            m_data_33 = br.ReadByte();
            m_data_34 = br.ReadByte();
            m_data_35 = br.ReadByte();
            m_data_36 = br.ReadByte();
            m_data_37 = br.ReadByte();
            m_data_38 = br.ReadByte();
            m_data_39 = br.ReadByte();
            m_data_40 = br.ReadByte();
            m_data_41 = br.ReadByte();
            m_data_42 = br.ReadByte();
            m_data_43 = br.ReadByte();
            m_data_44 = br.ReadByte();
            m_data_45 = br.ReadByte();
            m_data_46 = br.ReadByte();
            m_data_47 = br.ReadByte();
            m_data_48 = br.ReadByte();
            m_data_49 = br.ReadByte();
            m_data_50 = br.ReadByte();
            m_data_51 = br.ReadByte();
            m_data_52 = br.ReadByte();
            m_data_53 = br.ReadByte();
            m_data_54 = br.ReadByte();
            m_data_55 = br.ReadByte();
            m_data_56 = br.ReadByte();
            m_data_57 = br.ReadByte();
            m_data_58 = br.ReadByte();
            m_data_59 = br.ReadByte();
            m_data_60 = br.ReadByte();
            m_data_61 = br.ReadByte();
            m_data_62 = br.ReadByte();
            m_data_63 = br.ReadByte();
            m_data_64 = br.ReadByte();
            m_data_65 = br.ReadByte();
            m_data_66 = br.ReadByte();
            m_data_67 = br.ReadByte();
            m_data_68 = br.ReadByte();
            m_data_69 = br.ReadByte();
            m_data_70 = br.ReadByte();
            m_data_71 = br.ReadByte();
            m_data_72 = br.ReadByte();
            m_data_73 = br.ReadByte();
            m_data_74 = br.ReadByte();
            m_data_75 = br.ReadByte();
            m_data_76 = br.ReadByte();
            m_data_77 = br.ReadByte();
            m_data_78 = br.ReadByte();
            m_data_79 = br.ReadByte();
            m_data_80 = br.ReadByte();
            m_data_81 = br.ReadByte();
            m_data_82 = br.ReadByte();
            m_data_83 = br.ReadByte();
            m_data_84 = br.ReadByte();
            m_data_85 = br.ReadByte();
            m_data_86 = br.ReadByte();
            m_data_87 = br.ReadByte();
            m_data_88 = br.ReadByte();
            m_data_89 = br.ReadByte();
            m_data_90 = br.ReadByte();
            m_data_91 = br.ReadByte();
            m_data_92 = br.ReadByte();
            m_data_93 = br.ReadByte();
            m_data_94 = br.ReadByte();
            m_data_95 = br.ReadByte();
            m_data_96 = br.ReadByte();
            m_data_97 = br.ReadByte();
            m_data_98 = br.ReadByte();
            m_data_99 = br.ReadByte();
            m_data_100 = br.ReadByte();
            m_data_101 = br.ReadByte();
            m_data_102 = br.ReadByte();
            m_data_103 = br.ReadByte();
            m_data_104 = br.ReadByte();
            m_data_105 = br.ReadByte();
            m_data_106 = br.ReadByte();
            m_data_107 = br.ReadByte();
            m_data_108 = br.ReadByte();
            m_data_109 = br.ReadByte();
            m_data_110 = br.ReadByte();
            m_data_111 = br.ReadByte();
            m_data_112 = br.ReadByte();
            m_data_113 = br.ReadByte();
            m_data_114 = br.ReadByte();
            m_data_115 = br.ReadByte();
            m_data_116 = br.ReadByte();
            m_data_117 = br.ReadByte();
            m_data_118 = br.ReadByte();
            m_data_119 = br.ReadByte();
            m_data_120 = br.ReadByte();
            m_data_121 = br.ReadByte();
            m_data_122 = br.ReadByte();
            m_data_123 = br.ReadByte();
            m_data_124 = br.ReadByte();
            m_data_125 = br.ReadByte();
            m_data_126 = br.ReadByte();
            m_data_127 = br.ReadByte();
            m_data_128 = br.ReadByte();
            m_data_129 = br.ReadByte();
            m_data_130 = br.ReadByte();
            m_data_131 = br.ReadByte();
            m_data_132 = br.ReadByte();
            m_data_133 = br.ReadByte();
            m_data_134 = br.ReadByte();
            m_data_135 = br.ReadByte();
            m_data_136 = br.ReadByte();
            m_data_137 = br.ReadByte();
            m_data_138 = br.ReadByte();
            m_data_139 = br.ReadByte();
            m_data_140 = br.ReadByte();
            m_data_141 = br.ReadByte();
            m_data_142 = br.ReadByte();
            m_data_143 = br.ReadByte();
            m_data_144 = br.ReadByte();
            m_data_145 = br.ReadByte();
            m_data_146 = br.ReadByte();
            m_data_147 = br.ReadByte();
            m_data_148 = br.ReadByte();
            m_data_149 = br.ReadByte();
            m_data_150 = br.ReadByte();
            m_data_151 = br.ReadByte();
            m_data_152 = br.ReadByte();
            m_data_153 = br.ReadByte();
            m_data_154 = br.ReadByte();
            m_data_155 = br.ReadByte();
            m_data_156 = br.ReadByte();
            m_data_157 = br.ReadByte();
            m_data_158 = br.ReadByte();
            m_data_159 = br.ReadByte();
            m_data_160 = br.ReadByte();
            m_data_161 = br.ReadByte();
            m_data_162 = br.ReadByte();
            m_data_163 = br.ReadByte();
            m_data_164 = br.ReadByte();
            m_data_165 = br.ReadByte();
            m_data_166 = br.ReadByte();
            m_data_167 = br.ReadByte();
            m_data_168 = br.ReadByte();
            m_data_169 = br.ReadByte();
            m_data_170 = br.ReadByte();
            m_data_171 = br.ReadByte();
            m_data_172 = br.ReadByte();
            m_data_173 = br.ReadByte();
            m_data_174 = br.ReadByte();
            m_data_175 = br.ReadByte();
            m_data_176 = br.ReadByte();
            m_data_177 = br.ReadByte();
            m_data_178 = br.ReadByte();
            m_data_179 = br.ReadByte();
            m_data_180 = br.ReadByte();
            m_data_181 = br.ReadByte();
            m_data_182 = br.ReadByte();
            m_data_183 = br.ReadByte();
            m_data_184 = br.ReadByte();
            m_data_185 = br.ReadByte();
            m_data_186 = br.ReadByte();
            m_data_187 = br.ReadByte();
            m_data_188 = br.ReadByte();
            m_data_189 = br.ReadByte();
            m_data_190 = br.ReadByte();
            m_data_191 = br.ReadByte();
            m_data_192 = br.ReadByte();
            m_data_193 = br.ReadByte();
            m_data_194 = br.ReadByte();
            m_data_195 = br.ReadByte();
            m_data_196 = br.ReadByte();
            m_data_197 = br.ReadByte();
            m_data_198 = br.ReadByte();
            m_data_199 = br.ReadByte();
            m_data_200 = br.ReadByte();
            m_data_201 = br.ReadByte();
            m_data_202 = br.ReadByte();
            m_data_203 = br.ReadByte();
            m_data_204 = br.ReadByte();
            m_data_205 = br.ReadByte();
            m_data_206 = br.ReadByte();
            m_data_207 = br.ReadByte();
            m_data_208 = br.ReadByte();
            m_data_209 = br.ReadByte();
            m_data_210 = br.ReadByte();
            m_data_211 = br.ReadByte();
            m_data_212 = br.ReadByte();
            m_data_213 = br.ReadByte();
            m_data_214 = br.ReadByte();
            m_data_215 = br.ReadByte();
            m_data_216 = br.ReadByte();
            m_data_217 = br.ReadByte();
            m_data_218 = br.ReadByte();
            m_data_219 = br.ReadByte();
            m_data_220 = br.ReadByte();
            m_data_221 = br.ReadByte();
            m_data_222 = br.ReadByte();
            m_data_223 = br.ReadByte();
            m_data_224 = br.ReadByte();
            m_data_225 = br.ReadByte();
            m_data_226 = br.ReadByte();
            m_data_227 = br.ReadByte();
            m_data_228 = br.ReadByte();
            m_data_229 = br.ReadByte();
            m_data_230 = br.ReadByte();
            m_data_231 = br.ReadByte();
            m_data_232 = br.ReadByte();
            m_data_233 = br.ReadByte();
            m_data_234 = br.ReadByte();
            m_data_235 = br.ReadByte();
            m_data_236 = br.ReadByte();
            m_data_237 = br.ReadByte();
            m_data_238 = br.ReadByte();
            m_data_239 = br.ReadByte();
            m_data_240 = br.ReadByte();
            m_data_241 = br.ReadByte();
            m_data_242 = br.ReadByte();
            m_data_243 = br.ReadByte();
            m_data_244 = br.ReadByte();
            m_data_245 = br.ReadByte();
            m_data_246 = br.ReadByte();
            m_data_247 = br.ReadByte();
            m_data_248 = br.ReadByte();
            m_data_249 = br.ReadByte();
            m_data_250 = br.ReadByte();
            m_data_251 = br.ReadByte();
            m_data_252 = br.ReadByte();
            m_data_253 = br.ReadByte();
            m_data_254 = br.ReadByte();
            m_data_255 = br.ReadByte();
            m_data_256 = br.ReadByte();
            m_data_257 = br.ReadByte();
            m_data_258 = br.ReadByte();
            m_data_259 = br.ReadByte();
            m_data_260 = br.ReadByte();
            m_data_261 = br.ReadByte();
            m_data_262 = br.ReadByte();
            m_data_263 = br.ReadByte();
            m_data_264 = br.ReadByte();
            m_data_265 = br.ReadByte();
            m_data_266 = br.ReadByte();
            m_data_267 = br.ReadByte();
            m_data_268 = br.ReadByte();
            m_data_269 = br.ReadByte();
            m_data_270 = br.ReadByte();
            m_data_271 = br.ReadByte();
            m_data_272 = br.ReadByte();
            m_data_273 = br.ReadByte();
            m_data_274 = br.ReadByte();
            m_data_275 = br.ReadByte();
            m_data_276 = br.ReadByte();
            m_data_277 = br.ReadByte();
            m_data_278 = br.ReadByte();
            m_data_279 = br.ReadByte();
            m_data_280 = br.ReadByte();
            m_data_281 = br.ReadByte();
            m_data_282 = br.ReadByte();
            m_data_283 = br.ReadByte();
            m_data_284 = br.ReadByte();
            m_data_285 = br.ReadByte();
            m_data_286 = br.ReadByte();
            m_data_287 = br.ReadByte();
            m_data_288 = br.ReadByte();
            m_data_289 = br.ReadByte();
            m_data_290 = br.ReadByte();
            m_data_291 = br.ReadByte();
            m_data_292 = br.ReadByte();
            m_data_293 = br.ReadByte();
            m_data_294 = br.ReadByte();
            m_data_295 = br.ReadByte();
            m_data_296 = br.ReadByte();
            m_data_297 = br.ReadByte();
            m_data_298 = br.ReadByte();
            m_data_299 = br.ReadByte();
            m_data_300 = br.ReadByte();
            m_data_301 = br.ReadByte();
            m_data_302 = br.ReadByte();
            m_data_303 = br.ReadByte();
            m_data_304 = br.ReadByte();
            m_data_305 = br.ReadByte();
            m_data_306 = br.ReadByte();
            m_data_307 = br.ReadByte();
            m_data_308 = br.ReadByte();
            m_data_309 = br.ReadByte();
            m_data_310 = br.ReadByte();
            m_data_311 = br.ReadByte();
            m_data_312 = br.ReadByte();
            m_data_313 = br.ReadByte();
            m_data_314 = br.ReadByte();
            m_data_315 = br.ReadByte();
            m_data_316 = br.ReadByte();
            m_data_317 = br.ReadByte();
            m_data_318 = br.ReadByte();
            m_data_319 = br.ReadByte();
            m_data_320 = br.ReadByte();
            m_data_321 = br.ReadByte();
            m_data_322 = br.ReadByte();
            m_data_323 = br.ReadByte();
            m_data_324 = br.ReadByte();
            m_data_325 = br.ReadByte();
            m_data_326 = br.ReadByte();
            m_data_327 = br.ReadByte();
            m_data_328 = br.ReadByte();
            m_data_329 = br.ReadByte();
            m_data_330 = br.ReadByte();
            m_data_331 = br.ReadByte();
            m_data_332 = br.ReadByte();
            m_data_333 = br.ReadByte();
            m_data_334 = br.ReadByte();
            m_data_335 = br.ReadByte();
            m_data_336 = br.ReadByte();
            m_data_337 = br.ReadByte();
            m_data_338 = br.ReadByte();
            m_data_339 = br.ReadByte();
            m_data_340 = br.ReadByte();
            m_data_341 = br.ReadByte();
            m_data_342 = br.ReadByte();
            m_data_343 = br.ReadByte();
            m_data_344 = br.ReadByte();
            m_data_345 = br.ReadByte();
            m_data_346 = br.ReadByte();
            m_data_347 = br.ReadByte();
            m_data_348 = br.ReadByte();
            m_data_349 = br.ReadByte();
            m_data_350 = br.ReadByte();
            m_data_351 = br.ReadByte();
            m_data_352 = br.ReadByte();
            m_data_353 = br.ReadByte();
            m_data_354 = br.ReadByte();
            m_data_355 = br.ReadByte();
            m_data_356 = br.ReadByte();
            m_data_357 = br.ReadByte();
            m_data_358 = br.ReadByte();
            m_data_359 = br.ReadByte();
            m_data_360 = br.ReadByte();
            m_data_361 = br.ReadByte();
            m_data_362 = br.ReadByte();
            m_data_363 = br.ReadByte();
            m_data_364 = br.ReadByte();
            m_data_365 = br.ReadByte();
            m_data_366 = br.ReadByte();
            m_data_367 = br.ReadByte();
            m_data_368 = br.ReadByte();
            m_data_369 = br.ReadByte();
            m_data_370 = br.ReadByte();
            m_data_371 = br.ReadByte();
            m_data_372 = br.ReadByte();
            m_data_373 = br.ReadByte();
            m_data_374 = br.ReadByte();
            m_data_375 = br.ReadByte();
            m_data_376 = br.ReadByte();
            m_data_377 = br.ReadByte();
            m_data_378 = br.ReadByte();
            m_data_379 = br.ReadByte();
            m_data_380 = br.ReadByte();
            m_data_381 = br.ReadByte();
            m_data_382 = br.ReadByte();
            m_data_383 = br.ReadByte();
            m_data_384 = br.ReadByte();
            m_data_385 = br.ReadByte();
            m_data_386 = br.ReadByte();
            m_data_387 = br.ReadByte();
            m_data_388 = br.ReadByte();
            m_data_389 = br.ReadByte();
            m_data_390 = br.ReadByte();
            m_data_391 = br.ReadByte();
            m_data_392 = br.ReadByte();
            m_data_393 = br.ReadByte();
            m_data_394 = br.ReadByte();
            m_data_395 = br.ReadByte();
            m_data_396 = br.ReadByte();
            m_data_397 = br.ReadByte();
            m_data_398 = br.ReadByte();
            m_data_399 = br.ReadByte();
            m_data_400 = br.ReadByte();
            m_data_401 = br.ReadByte();
            m_data_402 = br.ReadByte();
            m_data_403 = br.ReadByte();
            m_data_404 = br.ReadByte();
            m_data_405 = br.ReadByte();
            m_data_406 = br.ReadByte();
            m_data_407 = br.ReadByte();
            m_data_408 = br.ReadByte();
            m_data_409 = br.ReadByte();
            m_data_410 = br.ReadByte();
            m_data_411 = br.ReadByte();
            m_data_412 = br.ReadByte();
            m_data_413 = br.ReadByte();
            m_data_414 = br.ReadByte();
            m_data_415 = br.ReadByte();
            m_data_416 = br.ReadByte();
            m_data_417 = br.ReadByte();
            m_data_418 = br.ReadByte();
            m_data_419 = br.ReadByte();
            m_data_420 = br.ReadByte();
            m_data_421 = br.ReadByte();
            m_data_422 = br.ReadByte();
            m_data_423 = br.ReadByte();
            m_data_424 = br.ReadByte();
            m_data_425 = br.ReadByte();
            m_data_426 = br.ReadByte();
            m_data_427 = br.ReadByte();
            m_data_428 = br.ReadByte();
            m_data_429 = br.ReadByte();
            m_data_430 = br.ReadByte();
            m_data_431 = br.ReadByte();
            m_data_432 = br.ReadByte();
            m_data_433 = br.ReadByte();
            m_data_434 = br.ReadByte();
            m_data_435 = br.ReadByte();
            m_data_436 = br.ReadByte();
            m_data_437 = br.ReadByte();
            m_data_438 = br.ReadByte();
            m_data_439 = br.ReadByte();
            m_data_440 = br.ReadByte();
            m_data_441 = br.ReadByte();
            m_data_442 = br.ReadByte();
            m_data_443 = br.ReadByte();
            m_data_444 = br.ReadByte();
            m_data_445 = br.ReadByte();
            m_data_446 = br.ReadByte();
            m_data_447 = br.ReadByte();
            m_data_448 = br.ReadByte();
            m_data_449 = br.ReadByte();
            m_data_450 = br.ReadByte();
            m_data_451 = br.ReadByte();
            m_data_452 = br.ReadByte();
            m_data_453 = br.ReadByte();
            m_data_454 = br.ReadByte();
            m_data_455 = br.ReadByte();
            m_data_456 = br.ReadByte();
            m_data_457 = br.ReadByte();
            m_data_458 = br.ReadByte();
            m_data_459 = br.ReadByte();
            m_data_460 = br.ReadByte();
            m_data_461 = br.ReadByte();
            m_data_462 = br.ReadByte();
            m_data_463 = br.ReadByte();
            m_data_464 = br.ReadByte();
            m_data_465 = br.ReadByte();
            m_data_466 = br.ReadByte();
            m_data_467 = br.ReadByte();
            m_data_468 = br.ReadByte();
            m_data_469 = br.ReadByte();
            m_data_470 = br.ReadByte();
            m_data_471 = br.ReadByte();
            m_data_472 = br.ReadByte();
            m_data_473 = br.ReadByte();
            m_data_474 = br.ReadByte();
            m_data_475 = br.ReadByte();
            m_data_476 = br.ReadByte();
            m_data_477 = br.ReadByte();
            m_data_478 = br.ReadByte();
            m_data_479 = br.ReadByte();
            m_data_480 = br.ReadByte();
            m_data_481 = br.ReadByte();
            m_data_482 = br.ReadByte();
            m_data_483 = br.ReadByte();
            m_data_484 = br.ReadByte();
            m_data_485 = br.ReadByte();
            m_data_486 = br.ReadByte();
            m_data_487 = br.ReadByte();
            m_data_488 = br.ReadByte();
            m_data_489 = br.ReadByte();
            m_data_490 = br.ReadByte();
            m_data_491 = br.ReadByte();
            m_data_492 = br.ReadByte();
            m_data_493 = br.ReadByte();
            m_data_494 = br.ReadByte();
            m_data_495 = br.ReadByte();
        }
        
        public virtual void Write(PackFileSerializer s, BinaryWriterEx bw)
        {
            bw.WriteUInt32(m_bytesAllocated);
            bw.WriteUInt32(m_pad0);
            bw.WriteUInt32(m_pad1);
            bw.WriteUInt32(m_pad2);
            bw.WriteByte(m_data_0);
            bw.WriteByte(m_data_1);
            bw.WriteByte(m_data_2);
            bw.WriteByte(m_data_3);
            bw.WriteByte(m_data_4);
            bw.WriteByte(m_data_5);
            bw.WriteByte(m_data_6);
            bw.WriteByte(m_data_7);
            bw.WriteByte(m_data_8);
            bw.WriteByte(m_data_9);
            bw.WriteByte(m_data_10);
            bw.WriteByte(m_data_11);
            bw.WriteByte(m_data_12);
            bw.WriteByte(m_data_13);
            bw.WriteByte(m_data_14);
            bw.WriteByte(m_data_15);
            bw.WriteByte(m_data_16);
            bw.WriteByte(m_data_17);
            bw.WriteByte(m_data_18);
            bw.WriteByte(m_data_19);
            bw.WriteByte(m_data_20);
            bw.WriteByte(m_data_21);
            bw.WriteByte(m_data_22);
            bw.WriteByte(m_data_23);
            bw.WriteByte(m_data_24);
            bw.WriteByte(m_data_25);
            bw.WriteByte(m_data_26);
            bw.WriteByte(m_data_27);
            bw.WriteByte(m_data_28);
            bw.WriteByte(m_data_29);
            bw.WriteByte(m_data_30);
            bw.WriteByte(m_data_31);
            bw.WriteByte(m_data_32);
            bw.WriteByte(m_data_33);
            bw.WriteByte(m_data_34);
            bw.WriteByte(m_data_35);
            bw.WriteByte(m_data_36);
            bw.WriteByte(m_data_37);
            bw.WriteByte(m_data_38);
            bw.WriteByte(m_data_39);
            bw.WriteByte(m_data_40);
            bw.WriteByte(m_data_41);
            bw.WriteByte(m_data_42);
            bw.WriteByte(m_data_43);
            bw.WriteByte(m_data_44);
            bw.WriteByte(m_data_45);
            bw.WriteByte(m_data_46);
            bw.WriteByte(m_data_47);
            bw.WriteByte(m_data_48);
            bw.WriteByte(m_data_49);
            bw.WriteByte(m_data_50);
            bw.WriteByte(m_data_51);
            bw.WriteByte(m_data_52);
            bw.WriteByte(m_data_53);
            bw.WriteByte(m_data_54);
            bw.WriteByte(m_data_55);
            bw.WriteByte(m_data_56);
            bw.WriteByte(m_data_57);
            bw.WriteByte(m_data_58);
            bw.WriteByte(m_data_59);
            bw.WriteByte(m_data_60);
            bw.WriteByte(m_data_61);
            bw.WriteByte(m_data_62);
            bw.WriteByte(m_data_63);
            bw.WriteByte(m_data_64);
            bw.WriteByte(m_data_65);
            bw.WriteByte(m_data_66);
            bw.WriteByte(m_data_67);
            bw.WriteByte(m_data_68);
            bw.WriteByte(m_data_69);
            bw.WriteByte(m_data_70);
            bw.WriteByte(m_data_71);
            bw.WriteByte(m_data_72);
            bw.WriteByte(m_data_73);
            bw.WriteByte(m_data_74);
            bw.WriteByte(m_data_75);
            bw.WriteByte(m_data_76);
            bw.WriteByte(m_data_77);
            bw.WriteByte(m_data_78);
            bw.WriteByte(m_data_79);
            bw.WriteByte(m_data_80);
            bw.WriteByte(m_data_81);
            bw.WriteByte(m_data_82);
            bw.WriteByte(m_data_83);
            bw.WriteByte(m_data_84);
            bw.WriteByte(m_data_85);
            bw.WriteByte(m_data_86);
            bw.WriteByte(m_data_87);
            bw.WriteByte(m_data_88);
            bw.WriteByte(m_data_89);
            bw.WriteByte(m_data_90);
            bw.WriteByte(m_data_91);
            bw.WriteByte(m_data_92);
            bw.WriteByte(m_data_93);
            bw.WriteByte(m_data_94);
            bw.WriteByte(m_data_95);
            bw.WriteByte(m_data_96);
            bw.WriteByte(m_data_97);
            bw.WriteByte(m_data_98);
            bw.WriteByte(m_data_99);
            bw.WriteByte(m_data_100);
            bw.WriteByte(m_data_101);
            bw.WriteByte(m_data_102);
            bw.WriteByte(m_data_103);
            bw.WriteByte(m_data_104);
            bw.WriteByte(m_data_105);
            bw.WriteByte(m_data_106);
            bw.WriteByte(m_data_107);
            bw.WriteByte(m_data_108);
            bw.WriteByte(m_data_109);
            bw.WriteByte(m_data_110);
            bw.WriteByte(m_data_111);
            bw.WriteByte(m_data_112);
            bw.WriteByte(m_data_113);
            bw.WriteByte(m_data_114);
            bw.WriteByte(m_data_115);
            bw.WriteByte(m_data_116);
            bw.WriteByte(m_data_117);
            bw.WriteByte(m_data_118);
            bw.WriteByte(m_data_119);
            bw.WriteByte(m_data_120);
            bw.WriteByte(m_data_121);
            bw.WriteByte(m_data_122);
            bw.WriteByte(m_data_123);
            bw.WriteByte(m_data_124);
            bw.WriteByte(m_data_125);
            bw.WriteByte(m_data_126);
            bw.WriteByte(m_data_127);
            bw.WriteByte(m_data_128);
            bw.WriteByte(m_data_129);
            bw.WriteByte(m_data_130);
            bw.WriteByte(m_data_131);
            bw.WriteByte(m_data_132);
            bw.WriteByte(m_data_133);
            bw.WriteByte(m_data_134);
            bw.WriteByte(m_data_135);
            bw.WriteByte(m_data_136);
            bw.WriteByte(m_data_137);
            bw.WriteByte(m_data_138);
            bw.WriteByte(m_data_139);
            bw.WriteByte(m_data_140);
            bw.WriteByte(m_data_141);
            bw.WriteByte(m_data_142);
            bw.WriteByte(m_data_143);
            bw.WriteByte(m_data_144);
            bw.WriteByte(m_data_145);
            bw.WriteByte(m_data_146);
            bw.WriteByte(m_data_147);
            bw.WriteByte(m_data_148);
            bw.WriteByte(m_data_149);
            bw.WriteByte(m_data_150);
            bw.WriteByte(m_data_151);
            bw.WriteByte(m_data_152);
            bw.WriteByte(m_data_153);
            bw.WriteByte(m_data_154);
            bw.WriteByte(m_data_155);
            bw.WriteByte(m_data_156);
            bw.WriteByte(m_data_157);
            bw.WriteByte(m_data_158);
            bw.WriteByte(m_data_159);
            bw.WriteByte(m_data_160);
            bw.WriteByte(m_data_161);
            bw.WriteByte(m_data_162);
            bw.WriteByte(m_data_163);
            bw.WriteByte(m_data_164);
            bw.WriteByte(m_data_165);
            bw.WriteByte(m_data_166);
            bw.WriteByte(m_data_167);
            bw.WriteByte(m_data_168);
            bw.WriteByte(m_data_169);
            bw.WriteByte(m_data_170);
            bw.WriteByte(m_data_171);
            bw.WriteByte(m_data_172);
            bw.WriteByte(m_data_173);
            bw.WriteByte(m_data_174);
            bw.WriteByte(m_data_175);
            bw.WriteByte(m_data_176);
            bw.WriteByte(m_data_177);
            bw.WriteByte(m_data_178);
            bw.WriteByte(m_data_179);
            bw.WriteByte(m_data_180);
            bw.WriteByte(m_data_181);
            bw.WriteByte(m_data_182);
            bw.WriteByte(m_data_183);
            bw.WriteByte(m_data_184);
            bw.WriteByte(m_data_185);
            bw.WriteByte(m_data_186);
            bw.WriteByte(m_data_187);
            bw.WriteByte(m_data_188);
            bw.WriteByte(m_data_189);
            bw.WriteByte(m_data_190);
            bw.WriteByte(m_data_191);
            bw.WriteByte(m_data_192);
            bw.WriteByte(m_data_193);
            bw.WriteByte(m_data_194);
            bw.WriteByte(m_data_195);
            bw.WriteByte(m_data_196);
            bw.WriteByte(m_data_197);
            bw.WriteByte(m_data_198);
            bw.WriteByte(m_data_199);
            bw.WriteByte(m_data_200);
            bw.WriteByte(m_data_201);
            bw.WriteByte(m_data_202);
            bw.WriteByte(m_data_203);
            bw.WriteByte(m_data_204);
            bw.WriteByte(m_data_205);
            bw.WriteByte(m_data_206);
            bw.WriteByte(m_data_207);
            bw.WriteByte(m_data_208);
            bw.WriteByte(m_data_209);
            bw.WriteByte(m_data_210);
            bw.WriteByte(m_data_211);
            bw.WriteByte(m_data_212);
            bw.WriteByte(m_data_213);
            bw.WriteByte(m_data_214);
            bw.WriteByte(m_data_215);
            bw.WriteByte(m_data_216);
            bw.WriteByte(m_data_217);
            bw.WriteByte(m_data_218);
            bw.WriteByte(m_data_219);
            bw.WriteByte(m_data_220);
            bw.WriteByte(m_data_221);
            bw.WriteByte(m_data_222);
            bw.WriteByte(m_data_223);
            bw.WriteByte(m_data_224);
            bw.WriteByte(m_data_225);
            bw.WriteByte(m_data_226);
            bw.WriteByte(m_data_227);
            bw.WriteByte(m_data_228);
            bw.WriteByte(m_data_229);
            bw.WriteByte(m_data_230);
            bw.WriteByte(m_data_231);
            bw.WriteByte(m_data_232);
            bw.WriteByte(m_data_233);
            bw.WriteByte(m_data_234);
            bw.WriteByte(m_data_235);
            bw.WriteByte(m_data_236);
            bw.WriteByte(m_data_237);
            bw.WriteByte(m_data_238);
            bw.WriteByte(m_data_239);
            bw.WriteByte(m_data_240);
            bw.WriteByte(m_data_241);
            bw.WriteByte(m_data_242);
            bw.WriteByte(m_data_243);
            bw.WriteByte(m_data_244);
            bw.WriteByte(m_data_245);
            bw.WriteByte(m_data_246);
            bw.WriteByte(m_data_247);
            bw.WriteByte(m_data_248);
            bw.WriteByte(m_data_249);
            bw.WriteByte(m_data_250);
            bw.WriteByte(m_data_251);
            bw.WriteByte(m_data_252);
            bw.WriteByte(m_data_253);
            bw.WriteByte(m_data_254);
            bw.WriteByte(m_data_255);
            bw.WriteByte(m_data_256);
            bw.WriteByte(m_data_257);
            bw.WriteByte(m_data_258);
            bw.WriteByte(m_data_259);
            bw.WriteByte(m_data_260);
            bw.WriteByte(m_data_261);
            bw.WriteByte(m_data_262);
            bw.WriteByte(m_data_263);
            bw.WriteByte(m_data_264);
            bw.WriteByte(m_data_265);
            bw.WriteByte(m_data_266);
            bw.WriteByte(m_data_267);
            bw.WriteByte(m_data_268);
            bw.WriteByte(m_data_269);
            bw.WriteByte(m_data_270);
            bw.WriteByte(m_data_271);
            bw.WriteByte(m_data_272);
            bw.WriteByte(m_data_273);
            bw.WriteByte(m_data_274);
            bw.WriteByte(m_data_275);
            bw.WriteByte(m_data_276);
            bw.WriteByte(m_data_277);
            bw.WriteByte(m_data_278);
            bw.WriteByte(m_data_279);
            bw.WriteByte(m_data_280);
            bw.WriteByte(m_data_281);
            bw.WriteByte(m_data_282);
            bw.WriteByte(m_data_283);
            bw.WriteByte(m_data_284);
            bw.WriteByte(m_data_285);
            bw.WriteByte(m_data_286);
            bw.WriteByte(m_data_287);
            bw.WriteByte(m_data_288);
            bw.WriteByte(m_data_289);
            bw.WriteByte(m_data_290);
            bw.WriteByte(m_data_291);
            bw.WriteByte(m_data_292);
            bw.WriteByte(m_data_293);
            bw.WriteByte(m_data_294);
            bw.WriteByte(m_data_295);
            bw.WriteByte(m_data_296);
            bw.WriteByte(m_data_297);
            bw.WriteByte(m_data_298);
            bw.WriteByte(m_data_299);
            bw.WriteByte(m_data_300);
            bw.WriteByte(m_data_301);
            bw.WriteByte(m_data_302);
            bw.WriteByte(m_data_303);
            bw.WriteByte(m_data_304);
            bw.WriteByte(m_data_305);
            bw.WriteByte(m_data_306);
            bw.WriteByte(m_data_307);
            bw.WriteByte(m_data_308);
            bw.WriteByte(m_data_309);
            bw.WriteByte(m_data_310);
            bw.WriteByte(m_data_311);
            bw.WriteByte(m_data_312);
            bw.WriteByte(m_data_313);
            bw.WriteByte(m_data_314);
            bw.WriteByte(m_data_315);
            bw.WriteByte(m_data_316);
            bw.WriteByte(m_data_317);
            bw.WriteByte(m_data_318);
            bw.WriteByte(m_data_319);
            bw.WriteByte(m_data_320);
            bw.WriteByte(m_data_321);
            bw.WriteByte(m_data_322);
            bw.WriteByte(m_data_323);
            bw.WriteByte(m_data_324);
            bw.WriteByte(m_data_325);
            bw.WriteByte(m_data_326);
            bw.WriteByte(m_data_327);
            bw.WriteByte(m_data_328);
            bw.WriteByte(m_data_329);
            bw.WriteByte(m_data_330);
            bw.WriteByte(m_data_331);
            bw.WriteByte(m_data_332);
            bw.WriteByte(m_data_333);
            bw.WriteByte(m_data_334);
            bw.WriteByte(m_data_335);
            bw.WriteByte(m_data_336);
            bw.WriteByte(m_data_337);
            bw.WriteByte(m_data_338);
            bw.WriteByte(m_data_339);
            bw.WriteByte(m_data_340);
            bw.WriteByte(m_data_341);
            bw.WriteByte(m_data_342);
            bw.WriteByte(m_data_343);
            bw.WriteByte(m_data_344);
            bw.WriteByte(m_data_345);
            bw.WriteByte(m_data_346);
            bw.WriteByte(m_data_347);
            bw.WriteByte(m_data_348);
            bw.WriteByte(m_data_349);
            bw.WriteByte(m_data_350);
            bw.WriteByte(m_data_351);
            bw.WriteByte(m_data_352);
            bw.WriteByte(m_data_353);
            bw.WriteByte(m_data_354);
            bw.WriteByte(m_data_355);
            bw.WriteByte(m_data_356);
            bw.WriteByte(m_data_357);
            bw.WriteByte(m_data_358);
            bw.WriteByte(m_data_359);
            bw.WriteByte(m_data_360);
            bw.WriteByte(m_data_361);
            bw.WriteByte(m_data_362);
            bw.WriteByte(m_data_363);
            bw.WriteByte(m_data_364);
            bw.WriteByte(m_data_365);
            bw.WriteByte(m_data_366);
            bw.WriteByte(m_data_367);
            bw.WriteByte(m_data_368);
            bw.WriteByte(m_data_369);
            bw.WriteByte(m_data_370);
            bw.WriteByte(m_data_371);
            bw.WriteByte(m_data_372);
            bw.WriteByte(m_data_373);
            bw.WriteByte(m_data_374);
            bw.WriteByte(m_data_375);
            bw.WriteByte(m_data_376);
            bw.WriteByte(m_data_377);
            bw.WriteByte(m_data_378);
            bw.WriteByte(m_data_379);
            bw.WriteByte(m_data_380);
            bw.WriteByte(m_data_381);
            bw.WriteByte(m_data_382);
            bw.WriteByte(m_data_383);
            bw.WriteByte(m_data_384);
            bw.WriteByte(m_data_385);
            bw.WriteByte(m_data_386);
            bw.WriteByte(m_data_387);
            bw.WriteByte(m_data_388);
            bw.WriteByte(m_data_389);
            bw.WriteByte(m_data_390);
            bw.WriteByte(m_data_391);
            bw.WriteByte(m_data_392);
            bw.WriteByte(m_data_393);
            bw.WriteByte(m_data_394);
            bw.WriteByte(m_data_395);
            bw.WriteByte(m_data_396);
            bw.WriteByte(m_data_397);
            bw.WriteByte(m_data_398);
            bw.WriteByte(m_data_399);
            bw.WriteByte(m_data_400);
            bw.WriteByte(m_data_401);
            bw.WriteByte(m_data_402);
            bw.WriteByte(m_data_403);
            bw.WriteByte(m_data_404);
            bw.WriteByte(m_data_405);
            bw.WriteByte(m_data_406);
            bw.WriteByte(m_data_407);
            bw.WriteByte(m_data_408);
            bw.WriteByte(m_data_409);
            bw.WriteByte(m_data_410);
            bw.WriteByte(m_data_411);
            bw.WriteByte(m_data_412);
            bw.WriteByte(m_data_413);
            bw.WriteByte(m_data_414);
            bw.WriteByte(m_data_415);
            bw.WriteByte(m_data_416);
            bw.WriteByte(m_data_417);
            bw.WriteByte(m_data_418);
            bw.WriteByte(m_data_419);
            bw.WriteByte(m_data_420);
            bw.WriteByte(m_data_421);
            bw.WriteByte(m_data_422);
            bw.WriteByte(m_data_423);
            bw.WriteByte(m_data_424);
            bw.WriteByte(m_data_425);
            bw.WriteByte(m_data_426);
            bw.WriteByte(m_data_427);
            bw.WriteByte(m_data_428);
            bw.WriteByte(m_data_429);
            bw.WriteByte(m_data_430);
            bw.WriteByte(m_data_431);
            bw.WriteByte(m_data_432);
            bw.WriteByte(m_data_433);
            bw.WriteByte(m_data_434);
            bw.WriteByte(m_data_435);
            bw.WriteByte(m_data_436);
            bw.WriteByte(m_data_437);
            bw.WriteByte(m_data_438);
            bw.WriteByte(m_data_439);
            bw.WriteByte(m_data_440);
            bw.WriteByte(m_data_441);
            bw.WriteByte(m_data_442);
            bw.WriteByte(m_data_443);
            bw.WriteByte(m_data_444);
            bw.WriteByte(m_data_445);
            bw.WriteByte(m_data_446);
            bw.WriteByte(m_data_447);
            bw.WriteByte(m_data_448);
            bw.WriteByte(m_data_449);
            bw.WriteByte(m_data_450);
            bw.WriteByte(m_data_451);
            bw.WriteByte(m_data_452);
            bw.WriteByte(m_data_453);
            bw.WriteByte(m_data_454);
            bw.WriteByte(m_data_455);
            bw.WriteByte(m_data_456);
            bw.WriteByte(m_data_457);
            bw.WriteByte(m_data_458);
            bw.WriteByte(m_data_459);
            bw.WriteByte(m_data_460);
            bw.WriteByte(m_data_461);
            bw.WriteByte(m_data_462);
            bw.WriteByte(m_data_463);
            bw.WriteByte(m_data_464);
            bw.WriteByte(m_data_465);
            bw.WriteByte(m_data_466);
            bw.WriteByte(m_data_467);
            bw.WriteByte(m_data_468);
            bw.WriteByte(m_data_469);
            bw.WriteByte(m_data_470);
            bw.WriteByte(m_data_471);
            bw.WriteByte(m_data_472);
            bw.WriteByte(m_data_473);
            bw.WriteByte(m_data_474);
            bw.WriteByte(m_data_475);
            bw.WriteByte(m_data_476);
            bw.WriteByte(m_data_477);
            bw.WriteByte(m_data_478);
            bw.WriteByte(m_data_479);
            bw.WriteByte(m_data_480);
            bw.WriteByte(m_data_481);
            bw.WriteByte(m_data_482);
            bw.WriteByte(m_data_483);
            bw.WriteByte(m_data_484);
            bw.WriteByte(m_data_485);
            bw.WriteByte(m_data_486);
            bw.WriteByte(m_data_487);
            bw.WriteByte(m_data_488);
            bw.WriteByte(m_data_489);
            bw.WriteByte(m_data_490);
            bw.WriteByte(m_data_491);
            bw.WriteByte(m_data_492);
            bw.WriteByte(m_data_493);
            bw.WriteByte(m_data_494);
            bw.WriteByte(m_data_495);
        }
    }
}
